### ISSUE TITLE
Add setup for cross-compiling

### ISSUE THREAD

**Issue by mwichmann** [SCons/cookbook#6]
Add a working example of setting up cross-compiling: set toolchain pieces, path to toolchain, etc.  Maybe command-line support for selecting target and getting the right things?

People building for embedded always seem to have this question.

Does PlatformIO have anything on this?

**Comment by urbasus** [comment]
Perhaps the content of [this SO question/answer](https://stackoverflow.com/questions/23898584/how-can-i-use-a-cross-compiler-with-scons) is enough to get started:

```
import os

env_options = {
    "CC"    : "nios2-linux-gnu-gcc",
    "CXX"   : "nios2-linux-gnu-g++",
    "LD"    : "nios2-linux-gnu-g++",
    "AR"    : "nios2-linux-gnu-ar",
    "STRIP" : "nios2-linux-gnu-strip",
}

env = Environment(**env_options)
env.Append(ENV = {'PATH' : os.environ['PATH']})
Export('env')
```
